kubernetes-controllers
otus-kuber-2020-04/kovtalex_platform pull request #3
Opened 2020-05-14 14:19 UTC by kovtalex

# Выполнено ДЗ №2

 - [X] Основное ДЗ
 - [X] Задание со *
 - [X] Задание со **

## В процессе сделано:
 - Развернут кластер kind
 - Изучена работа ReplicaSet, Deployment, DaemonSet
 - Опробованы обновления Deployments
 - Изучено применение Probes

## Как запустить проект:
 - Выполнить **kubectl apply -f paymentservice-deployment.yaml -f frontend-deployment.yaml**

## Как проверить работоспособность:
 - Выполнить **kubectl get deployments**

## PR checklist:
 - [X] Выставлен label с темой домашнего задания

2020-05-14 19:33 UTC, Jasstkn requested changes
Добрый вечер! Проверила ваше домашнее задание - все сделано хорошо :) Оставила комментарии по заданиям со звездочкой - жду доработок! Также хотела бы попросить оставлять более подробный README, чтобы в нем также был вывод команд и какие параметры изменены - это облегчит проверку, а также поможет вам более лучше запоминать проделанные шаги :)

2020-05-14 19:33 UTC, Jasstkn commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +        operator: Exists
Вы начали копать в нужную сторону, но выбрали не универсальное решение для tolerations.
Предлагаю вам подробнее ознакомиться с документацией:
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#concepts -> секция Note и с официальным манифестом для node exporter: https://github.com/coreos/kube-prometheus/blob/master/manifests/node-exporter-daemonset.yaml

2020-05-14 19:33 UTC, Jasstkn commented on kubernetes-controllers/paymentservice-deployment-reverse.yaml
> +      maxUnavailable: 1
В вашем варианте получается сначала будет удалена одна реплика из старого реплика сет, а потом создана одна новая. В задании требуется одновременное создание нового и удаление старого. Попробуйте поиграться со значениями, чтобы добиться нужного результата и найти самый безопасный вариант выкатки.

2020-05-15 09:35 UTC, Jasstkn approved these changes
Отличная работа =) Желаю успехов со следующими домашками!

2020-05-15 09:35 UTC, merged

2020-05-15 09:38 UTC, kovtalex commented on kubernetes-controllers/paymentservice-deployment-reverse.yaml
> +      maxUnavailable: 1
maxSurge: 1
maxUnavailable: 1

2020-05-15 09:39 UTC, kovtalex commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +        operator: Exists
Спасибо за комментарии) Учту при написании README. Также расширил описание относительно заданий со *.

tolerations:
- operator: Exists